### ISSUE TITLE
tour: [한글 오타가 있습니다. there's typo with Korean mode]

### ISSUE THREAD

**Issue by JeesubKim** [golang-ko/tour#17]
Context: https://go-tour-ko.appspot.com/flowcontrol/9

**_Please refer to below that I marked in the middle of sentence_**

Switch
switch 구문은 연속적인 if - else 구문을 사용하는 짧은 방안입니다. 그것은 값이 조건문과 같은 첫 번째 case를 실행합니다.

Go의 switch는 Go는 뒤이어 오는 모든 case를 실행하는 것이 아니라 오직 첫 번째 선택된 케이스만을 실행한다는 점을

**> 제회 (x) 제외 (o)**

하고는 C와 C++, Java, Javascript, PHP와 유사합니다. 효과적으로, break 구문은 위의 언어들에서는 각 case의 끝 부분에 필요하지만, Go에서는 자동으로 break가 제공됩니다. 다른 중요한 차이점은 Go의 switch case는 상수일 필요가 없으며 그 값들은 정수일 필요도 없습니다.

**Comment by umi0410** [comment]
좋은 제보 감사드립니다.
#18에서 Merge 되었습니다.
