### ISSUE TITLE
[flowcontrol/4] 조금 더 자연스러운  문장으로 바꾸면 좋겠습니다.

### ISSUE THREAD

**Issue by dextto** [golang-ko/tour#26]
- 원문: If you omit the loop condition it loops forever, so an infinite loop is compactly expressed.
- 번역문: 만약 당신이 그것이 영원한 반복문에서 반복 조건을 생략한다면, 그것을 통해 무한 루프 또한 간편히 표현될 수 있습니다.

번역문이 기계번역체여서 조금 더 자연스러운 문장으로 바꾸면 좋겠습니다.

**Comment by umi0410** [comment]
PR merge해 이슈 닫겠습니다. 감사합니다.
